"""Criacao da tabela abastecimento

Revision ID: 211f0e1b350a
Revises: 
Create Date: 2026-01-21 02:09:17.596485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '211f0e1b350a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('abastecimentos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_posto', sa.Integer(), nullable=False),
    sa.Column('data_hora', sa.DateTime(), nullable=True),
    sa.Column('tipo_combustivel', sa.Enum('GASOLINA', 'ETANOL', 'DIESEL', name='tipocombustivel'), nullable=False),
    sa.Column('preco_por_litro', sa.Float(), nullable=False),
    sa.Column('volume_abastecido', sa.Float(), nullable=False),
    sa.Column('cpf_motorista', sa.String(), nullable=False),
    sa.Column('improper_data', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('abastecimentos')
    # ### end Alembic commands ###
